### ISSUE TITLE
[Feature Request] Standalone "VRM Spring Bone to Dynamic Bone" converter

### ISSUE THREAD

**Issue by andreiagmu** [esperecyan/UniVRMExtensions#1]
Hi! I came across this converter while I was looking for a tool to convert VRM Spring Bones (and Colliders) to Dynamic Bones.
Is it possible to add a standalone tool/wizard to _only_ convert the model's swaying objects, without the need for the VRChat SDK and the other conversion features?

I'm using Unity 2021.2.6f1, so the VRCSDK 3.0-avatar isn't compatible (it gives compilation errors related to ScriptableBuildPipeline).
I'm using VRM/VRoid Studio models on my game, I'm not using VRChat, so I only needed the Swaying bones conversion feature.

**Comment by esperecyan** [comment]
I implemented this feature in UniVRMExtensions-2.7.1.

![](https://user-images.githubusercontent.com/3625160/150716037-776cd348-c752-4020-ba11-bd95490c8fde.png)

**Comment by andreiagmu** [comment]
Great! I'll test it soon
Thank you very much for the support! :D
