### ISSUE TITLE
Original VRMSpringBone/ColliderGroup components aren't being deleted after conversion to DynamicBone/DynamicBoneCollider

### ISSUE THREAD

**Issue by andreiagmu** [esperecyan/UniVRMExtensions#3]
I'm not sure if that behavior (keeping the original components after the conversion) is intended, or not.
But this seems like a bug, it would make sense to delete the original VRMSpringBone components after conversion to DynamicBone.
Also, DynamicBone doesn't work if the original VRMSpringBones are still present on the character at the same time.

**Comment by esperecyan** [comment]
Thank you for your request. I will consider implementing it.

**Comment by andreiagmu** [comment]
Thanks! Maybe a new bool (or an enum?) could be added on the wizard, something like "Delete Original Swaying Objects" or "Keep Original Swaying Objects".

**Comment by esperecyan** [comment]
I implemented this feature in UniVRMExtensions-3.0.0.

**Comment by andreiagmu** [comment]
The feature worked correctly, thanks for implementing it!

The name of the new bool field became truncated on the Wizard. ("Remove swaying objects f")
Having more space on the left to show the name of the fields, or having a tooltip when you hover the mouse over the bool's name, I think would help the user to understand what the feature does.
![capture_20220129_095211_002](https://user-images.githubusercontent.com/3398672/151662379-ad057ac1-06ca-46f2-8252-2eac6687d6e7.png)

**Comment by esperecyan** [comment]
Thank you for the report, I fixed in v3.0.1.

**Comment by andreiagmu** [comment]
> Thank you for the report, I fixed in v3.0.1.

Great, thanks for the label fix! :D
