### ISSUE TITLE
"Parameters conversion algorithm" label is cut off in the Wizard

### ISSUE THREAD

**Issue by andreiagmu** [esperecyan/UniVRMExtensions#4]
"Parameters conversion algorithm" label is cut off in the Wizard. ("Parameters conversion al")
There are also some odd empty spaces at the right and below that label. (label isn't aligned with its Mono Script reference selector)

I think adding a [Tooltip] (displayed when the user hovers mouse pointer over the label), showing the full name of the field ("Parameters conversion algorithm"), would contribute to user experience.
I'm not sure if the localization strings will work with the Tooltip, but in theory, they should work.

Also, there's a small typo on another localized string:
"Remove swaying objects from Convertion source"
"Convertion" should be "Conversion" instead.

![capture_20220130_073817_002](https://user-images.githubusercontent.com/3398672/151696580-5529ae46-da98-440f-b88c-581798a84211.png)

**Comment by esperecyan** [comment]
I have addressed this issue in v3.0.2. Thank you for reporting it!

**Comment by andreiagmu** [comment]
Great, I updated the package here.
Thank you for addressing it!
