### ISSUE TITLE
Error - "There is no "Convert" static method with matching parameters.

### ISSUE THREAD

**Issue by winrymittens** [esperecyan/UniVRMExtensions#6]
![Screenshot 2022-08-28 143845](https://user-images.githubusercontent.com/112307344/187061157-511a9ec5-765d-4b66-9911-ae857f5df075.png)
![Screenshot 2022-08-28 143901](https://user-images.githubusercontent.com/112307344/187061158-56415075-e9e1-436f-b464-0cb2a54b3e59.png)

The error does not go away even though I have dragged the converter script provided into its place. What should I do here?

**Comment by esperecyan** [comment]
Am I correct that you mean “I would like to know more about how to set up my own swaying object conversion algorithm”?

**Comment by winrymittens** [comment]
I want to attach 3D hair from Booth on VRM model. (https://booth.pm/en/items/3479904)

The hair has Dynamic Bone.

I want to convert Dynamic Bone to VRM Spring bone (to use on VRM).

I tried to use the conversion Dynamic Bone > VRM Spring Bone but I don't know what to put under "Parameters conversion algorithm." 

What should I put there? 

Or am I doing this wrong? Can I actually convert the hair Dynamic Bone to VRM Spring bone?

**Comment by winrymittens** [comment]
I attach the 3D hair to my VRM head. The hair is 'For Mariel' and the bone is Dynamic Bone. I am looking for a way to convert Dynamic Bone to VRM Spring Bone because I want to use on VRM.

![image](https://user-images.githubusercontent.com/112307344/187061764-fee1b4bc-ae81-4c30-a054-0dcf6d86a4d4.png)

**Comment by esperecyan** [comment]
If you use the default algorithm, leave the Algorithm field empty.

**Comment by winrymittens** [comment]
Okay, thank you! It works. Sorry for bothering you with a small issue and thank you for your response.
