### ISSUE TITLE
VKET link is down. Consider english version on github.

### ISSUE THREAD

**Issue by DrBomb** [esperecyan/UniVRMExtensions#9]
Title

**Comment by esperecyan** [comment]
VketStore is under maintenance.
https://twitter.com/Virtual_Market_/status/1639207156682752003

Please download the installer from BOOTH.
https://pokemori.booth.pm/items/1788660

**Comment by DrBomb** [comment]
Boothには英語ないのに？

**Comment by esperecyan** [comment]
配布しているインストーラーはまったく同じファイルです。
